### PR TITLE
Add policy resolver hook

### PR DESCRIPTION
**Pull request by blaggacao**
It commonly occurs that policy resolution does not involve
http, eg. in case of local caching.
This commit introduces a hook to implement custom resolvers.
It also polishes naming as required by this implementation.

### CODE REVIEW

**Comment by blaggacao** [comment]
@etobella Also a policy cached policy property would be interesting:
- If i have to sign many documents in a row, I can declare the policy object globally and use spare the time for policy fetching and signature calculation having it stored in an object cache. Would you agree / accept a PR?

**Comment by blaggacao** [comment]
Note: removal of the `PolicyId` class was indicated as it's only method accessed an undefined property (`self.identifier`) indicating the normalized form would be moving that method to the special implementation of `PolicyId`class: the `GenericPolicyId` class. (despite the naming which suggested an inverse relationship)

**Comment by blaggacao** [comment]
@etobella Test failure is due to a failed URL handshake when trying to query the policy, therefore unrelated to those changes.

**Comment by etobella** [comment]
@blaggacao Tests have been fixed. I relaunched travis in order to check that everything is right

**Comment by etobella** [comment]
You need to rebase in order to check that everything is fine. Could you please?

**Comment by blaggacao** [comment]
@etobella Ok, thank you so much! Let's see how it goes. I included a couple of other fixes/improvements as I'm using my fork now for development purpose, If you don't agree with anything, please kindly ask me to extract a commit into a separate PR.

**Comment by blaggacao** [comment]
@etobella 

As for codecov it looks like the unspecific implementation of `validate_policy_node` which does not depend on initialized value (no policy cache) would not be tested with the current adaptions.

I construed a use case of something like:
- If I don't know the chosen implementation I can use the `Policy` class to verify it anyways (though not optimized).
- However, this is only a vague idea of why this was implemented on the generic level. Maybe there is no use case for such.
- In the latter case, it would be more correct to just define the interface of this method in the `Policy` class.

How should I adapt?

**Comment by etobella** [comment]
Remove it from policy (only a pass) and keep it on the Generic, I think it is the best approach.

By the way, I didn't know the usage of `ElementMaker`, really interesting :smile:

**Comment by blaggacao** [comment]
@etobella Thanks for your input. Please see the latest commit, I chose `NotImplementedError` instead. Also naming the `Policy` class `BasePolicy` better reveals it's character and role. I hope you're fine with it.

**Review by etobella — APPROVED** [review]
Great for  me!

**Comment by etobella** [comment]
Merging it, I will not create a new version until we finish the issues you commented #7 #6

**Comment by blaggacao** [comment]
Perfect, I'll retake shortly, had another priority issue coming in...

**Pull request merged**
