### PR TITLE
[FIX]: policy: Fill the Identifier and name elements

### PR DESCRIPTION
**Pull request by JulienAlardot**
As it makes no sense to have the data and generate the elements,
but leave them empty. This aims to fix that issue

Signed-off-by: Julien Alardot (jual) <jual@odoo.com>

### CODE REVIEW

**Comment by rafaurl** [comment]
same problem here trying to sign for TicketBai, where SigPolicyId/Identifier is compulsory.

**Comment by JulienAlardot** [comment]
@etobella Could you take a look at this PR when you have the time?

**Review by etobella — APPROVED** [review]

**Comment by etobella** [comment]
Makes sense, let's wait for GH Actions

**Comment by etobella** [comment]
Can you execute pre-commit please?

**Comment by etobella** [comment]
Created a new version on pip with the change

**Comment by JulienAlardot** [comment]
> Created a new version on pip with the change

Seems like the `requirements.txt` and `test-requirements.txt` are missing from the pypi package

**Comment by etobella** [comment]
I think it is fixed now #18 New version uploaded on pypi

**Comment by JulienAlardot** [comment]
@etobella I don't see a new version on pypi

**Pull request merged**
